### ISSUE TITLE
String parameters cannot propagate over design

### ISSUE THREAD

**Issue by mtdudek** [zachjs/sv2v#147]
Hi,
I'm using sv2v version v0.0.7-32-geae46b7.
I was trying to build ibex for arty with flow sv2v->yosys->vivado and I've encountered this issue.

SRAMInitFile is string like parameter that is passed further to memory module as its MemInitFile parameter.
By default MemInitFile parameter is size 1 and it cannot contain value of SRAMInitFile parameter resulting in error when $readmemh is run by yosys to initialize memory.

To fix this issue I changed:
`parameter  SRAMInitFile = ""` to `parameter [8*100:1] SRAMInitFile = ""`

To run this flow you can use this edalize [branch](https://github.com/antmicro/edalize/tree/surelog). It has everything you need to launch sv2v as part of toolchain. 
Also add this to your top_artya7.core
```
synth_surelog:
    default_tool: vivado
    filesets:
      - files_rtl_artya7
      - files_constraints
    toplevel: top_artya7
    parameters:
      - SRAMInitFile
      - PRIM_DEFAULT_IMPL=prim_pkg::ImplXilinx
    tools:
      vivado:
        part: "xc7a100tcsg324-1"  # Default to Arty A7-100
        synth: "yosys"
        yosys_synth_options: ['-iopad', '-family xc7', '-run :check', "frontend=sv2v"]
        yosys_read_options: ['-DPRIM_DEFAULT_IMPL=prim_pkg::ImplXilinx','-noassert','-defer']
        frontend_options: ['--write=adjacent', '-DSYNTHESIS']
```
Now you can build with command`fusesoc --cores-root=. run --build --tool vivado --target=synth_surelog lowrisc:ibex:top_artya7 --part xc7a35ticsg324-1L --SRAMInitFile="../../../examples/sw/led/led.vmem"`
